beer_ratings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

beer_ratings_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("beer/", include("beer_ratings_app.urls"))
]

ratings/urls.py
from django.urls import path
from . import views

app_name = 'ratings'

urlpatterns = [
    path('', views.home, name='home'),
    path('beers/', views.show_beers, name='show_beers'),
    path('beers/new/', views.create_beer, name='create_beer'),
    path('beers/<int:beer_id>/delete/', views.delete_beer, name='delete_beer'),
    path('beers/<int:beer_id>/', views.show_beer, name='show_beer'),
    path('beers/<int:beer_id>/edit/', views.edit_beer, name='edit_beer'),
    path('beers/<int:beer_id>/reviews/',
         views.show_reviews, name='show_reviews'),
    path('beers/<int:beer_id>/reviews/new/',
         views.create_review, name='create_review'),
    path('beers/<int:beer_id>/reviews/<int:review_id>/',
         views.show_review, name='show_review'),
    path('beers/<int:beer_id>/reviews/<int:review_id>/edit/',
         views.edit_review, name='edit_review'),
    path('beers/<int:beer_id>/reviews/<int:review_id>/delete/',
         views.delete_review, name='delete_review'),
]

ratings/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Beer(models.Model):
    name = models.CharField(max_length=255)


class Review(models.Model):
    beer = models.ForeignKey(
        'Beer', on_delete=models.CASCADE, related_name='reviews')

    # star ratings
    STAR_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    stars = models.PositiveSmallIntegerField(choices=STAR_CHOICES, default=3)

    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, related_name='reviews')

ratings/forms.py
from django.forms import ModelForm
from .models import Beer, Review


class BeerForm(ModelForm):
    class Meta:
        model = Beer
        fields = ['name']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['stars', 'title', 'content']
        exclude = ['beer', 'author']

ratings/views.py
from django import http
from django.shortcuts import redirect, render
from .forms import BeerForm, ReviewForm
from django.http import HttpResponse
from .models import Beer, Review


# Helper methods
def get_beer(beer_id):
    return Beer.objects.get(id=beer_id)


def get_review(review_id):
    return Review.objects.get(id=review_id)


# Views
def create_beer(request):
    if request.method == 'POST':
        filled_out_beer_form = BeerForm(request.POST)
        new_beer = filled_out_beer_form.save()
        return redirect('ratings:show_beer', beer_id=new_beer.id)
    else:
        beer_form = BeerForm()
        context = {'form': beer_form, 'type_of_form': 'New'}
        return render(request, 'ratings/beer_form.html', context)


def show_beer(request, beer_id):
    beer = get_beer(beer_id)
    context = {'beer': beer}
    return render(request, 'ratings/beer.html', context)


def show_beers(request):
    beers = Beer.objects.all()
    context = {'beers': beers}
    return render(request, 'ratings/beers_list.html', context)


def edit_beer(request, beer_id):
    beer = get_beer(beer_id)

    if request.method == 'POST':
        filled_out_beer_form = BeerForm(request.POST, instance=beer)
        new_beer = filled_out_beer_form.save()
        return redirect('ratings:show_beer', beer_id=new_beer.id)
    else:
        beer_form = BeerForm(instance=beer)
        context = {'form': beer_form, 'type_of_form': 'Edit'}
        return render(request, 'ratings/beer_form.html', context)


def delete_beer(request, beer_id):
    beer = get_beer(beer_id)
    beer.delete()
    return redirect('ratings:show_beers')


def home(request):
    reviews = Review.objects.filter(author=request.user)
    context = {'reviews': reviews}
    return render(request, 'ratings/home.html', context)

# Review views


def create_review(request, beer_id):
    beer = get_beer(beer_id)

    if request.user.is_authenticated:
        if request.method == 'POST':
            filled_out_review_form = ReviewForm(request.POST)
            new_review = filled_out_review_form.save(commit=False)
            new_review.beer = beer
            new_review.author = request.user
            new_review.save()
            return redirect('ratings:show_reviews', beer_id=beer_id)
        else:
            review_form = ReviewForm()
            context = {'form': review_form,
                       'type_of_form': 'New', 'beer': beer}
            return render(request, 'ratings/review_form.html', context)

    return redirect('ratings:home')


def show_reviews(request, beer_id):
    beer = get_beer(beer_id)
    reviews = Review.objects.filter(beer=beer)
    context = {'beer': beer, 'reviews': reviews}
    return render(request, 'ratings/beer_reviews.html', context)


def show_review(request, beer_id, review_id):
    beer = get_beer(beer_id)
    review = get_review(review_id)

    context = {'beer': beer, 'review': review}

    return render(request, 'ratings/review.html', context)


def edit_review(request, beer_id, review_id):
    beer = get_beer(beer_id)
    review = get_review(review_id)

    if request.method == 'POST':
        filled_out_review_form = ReviewForm(request.POST, instance=review)
        new_review = filled_out_review_form.save()
        new_review.save()
        return redirect('ratings:show_review', beer_id=beer_id, review_id=review_id)
    else:
        review_form = ReviewForm(instance=review)
        context = {'form': review_form,
                   'type_of_form': 'Edit', 'beer': beer}
        return render(request, 'ratings/review_form.html', context)


def delete_review(request, beer_id, review_id):
    review = get_review(review_id)
    review.delete()
    return redirect('ratings:show_reviews', beer_id=beer_id)

ratings/templates/ratings/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Beer Reviews{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>body{margin:10px 0px 0px 15px;}</style>
</head>
<body>
    {% if user.is_authenticated %}
        <p>Hi {{ user.username }}!</p>
        <a href="{% url 'ratings:home' %}">Home</a>
        <a href="{% url 'logout' %}">Log Out</a>
        {% block content %}
        {% endblock content %}
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
</body>
</html>

ratings/templates/ratings/beer.html
{% extends 'ratings/base.html' %}

{% block title %}{{ beer.name }}{% endblock title %}

{% block content %}
    <h1>{{ beer.name }}</h1>
    <a href="{% url 'ratings:edit_beer' beer_id=beer.id %}">Edit</a>
    <a href="{% url 'ratings:delete_beer' beer_id=beer.id %}">Delete</a>
    
    <br>
    <br>
    <a href="{% url 'ratings:show_reviews' beer_id=beer.id %}">Show Reviews</a>
    <br>
    <a href="{% url 'ratings:show_beers' %}">Back to Beers</a>
{% endblock content %}

ratings/templates/ratings/beer_form.html
{% extends 'ratings/base.html' %}

{% block title %}{{ type_of_form }} Beer{% endblock title %}

{% block content %}
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

ratings/templates/ratings/beer_reviews.html
{% extends 'ratings/base.html' %}

{% block title %}Reviews For {{ beer.name }}{% endblock title %}

{% block content %}
    <h1>Reviews For {{ beer.name }}</h1>
    <ul>
        {% for review in reviews %}
            <li><a href="{% url 'ratings:show_review' review_id=review.id beer_id=beer.id %}">{{ review.title }}</a></li>
        {% endfor %}
    </ul>

    <a href="{% url 'ratings:create_review' beer_id=beer.id %}">New Review</a>
    <br>
    <a href="{% url 'ratings:show_beer' beer_id=beer.id %}">Back To {{beer.name}}</a>
{% endblock content %}

ratings/templates/ratings/beers_list.html
{% extends 'ratings/base.html' %}

{% block title %}Beers{% endblock title %}

{% block content %}
    <h1>Beers</h1>
    <ul>
        {% for beer in beers %}
            <li><a href="{% url 'ratings:show_beer' beer_id=beer.id %}">{{ beer.name }}</a></li>    
        {% endfor %}
    </ul>

    <a href="{% url 'ratings:create_beer' %}">New</a>
    <a href="{% url 'ratings:home' %}">Home</a>
{% endblock content %}

ratings/templates/ratings/home.html
{% extends 'ratings/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <br>
    <p>This is home</p>
    <p>Here are the reviews you've made:</p>
    
    <ul>
        {% for review in reviews %}
            <li><a href="{% url 'ratings:show_review' review_id=review.id beer_id=review.beer.id %}">{{review.title}}</a></li>        
        {% endfor %}    
    </ul>

    <a href="{% url 'ratings:show_beers' %}">List Beers</a>
{% endblock content %}

ratings/templates/ratings/review.html
{% extends 'ratings/base.html' %}

{% block title %}Review For {{ beer.name }}{% endblock title %}

{% block content %}
    <h1>Review For {{ beer.name }}</h1>
    {% comment %} <a href="{% url 'ratings:edit_beer' beer_id=beer.id %}">Edit</a> {% endcomment %}
    {% comment %} <a href="{% url 'ratings:delete_beer' beer_id=beer.id %}">Delete</a> {% endcomment %}
    
    <br>
    <h2>{{review.title}}</h2>
    <p>Stars: {{review.stars}}</p>
    <p>{{review.content}}</p>
    <p>Written by: {{review.author}}</p>

    <br>
    {% if user == review.author %}
        <a href="{% url 'ratings:edit_review' beer_id=beer.id review_id=review.id %}">Edit</a>
        <a href="{% url 'ratings:delete_review' beer_id=beer.id review_id=review.id %}">Delete</a>
    {% endif %}

    <br>
    <a href="{% url 'ratings:show_reviews' beer_id=beer.id %}">Back To Reviews</a>
{% endblock content %}

ratings/templates/ratings/review_form.html
{% extends 'ratings/base.html' %}

{% block title %}{{ type_of_form }} Review of {{ beer.name }}{% endblock title %}

{% block content %}
    <h1>{{type_of_form}} Review of {{beer.name}}</h1>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}